"""empty message

Revision ID: 0c558a37c190
Revises: d6e9ace8d496
Create Date: 2021-11-22 16:41:30.437494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c558a37c190'
down_revision = 'd6e9ace8d496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_description'), 'restaurant', ['description'], unique=False)
    op.create_index(op.f('ix_restaurant_location'), 'restaurant', ['location'], unique=True)
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('restaurantID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantID'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_description'), 'dish', ['description'], unique=False)
    op.create_index(op.f('ix_dish_name'), 'dish', ['name'], unique=True)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restaurantID', sa.Integer(), nullable=True),
    sa.Column('dishID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishID'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['restaurantID'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewID'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('review')
    op.drop_index(op.f('ix_dish_name'), table_name='dish')
    op.drop_index(op.f('ix_dish_description'), table_name='dish')
    op.drop_table('dish')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_location'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_description'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
